name: footbase
channels:
  - defaults
dependencies:
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libkrb5=1.21.3
  - libpng=1.6.50
  - libpq=17.6
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nest-asyncio=1.6.0
  - numexpr=2.14.1
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openjpeg=2.5.2
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.4
  - pcre2=10.46
  - pillow=11.1.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.8.3
      - aiosignal==1.4.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - beautifulsoup4==4.11.1
      - certifi==2020.12.5
      - chardet==4.0.0
      - charset-normalizer==2.1.1
      - coverage==7.11.0
      - frozenlist==1.8.0
      - idna==2.10
      - iniconfig==2.3.0
      - multidict==6.7.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - pytest==7.2.0
      - pytest-aiohttp==1.0.4
      - pytest-asyncio==0.23.8
      - pytest-cov==4.0.0
      - pytest-mock==3.6.0
      - requests==2.25.1
      - soupsieve==2.8
      - understat==0.1.12
      - urllib3==1.26.5
      - yarl==1.22.0

